disqus_shortname: 
github_shortname: IwYvI
uyan_uid: 2115288

# Header
menu:
  - page: home
    directory: .
  - page: archive
    directory: archives/
  - page: work
    directory: works/
  - page: about
    directory: about/

rss: /atom.xml

# highlightjs: vs

# Content
excerpt_link: Read More

# Theme version
version: 0.1.0

# Miscellaneous
favicon: /favicon.ico
