disqus_shortname: iwyvi
github_shortname: IwYvI

# Header
menu:
  - page: home
    directory: .
  - page: archive
    directory: archives/
  - page: work
    directory: works/
  - page: about
    directory: about/

rss: /atom.xml

# highlightjs: vs

# Content
excerpt_link: Read More

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive


# widget behavior
archive_type: 'monthly'
show_count: false

# Theme version
version: 0.0.0

# Miscellaneous
favicon: /favicon.ico
